# Generated by Django 5.1.3 on 2024-11-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='p_creator',
            new_name='p_manager',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='t_creator',
            new_name='t_manager',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('manager', 'Project Manager'), ('teammate', 'Project Teammate')], max_length=10),
        ),
    ]
